server:
  port: ${BE_PORT}
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PW}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: ${SQL_LOGGING_LEVEL}

jwt:
  secret: "${JWT_SECRET_TOKEN}"

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_CALLBACK_URI}

  authorization-uri: ${KAKAO_AUTH_URI}
  token-uri: ${KAKAO_TOKEN_URI}
  user-info-uri: ${KAKAO_USER_INFO_URI}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  redirect-uri: ${GOOGLE_CALLBACK_URI}
  client-secret: ${GOOGLE_SECRET}

  authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
  token-uri: ${GOOGLE_TOKEN_URI}
  user-info-uri: ${GOOGLE_USER_INFO_URI}

