spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PW}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  config: classpath:logback.xml

jwt:
  secret: ${JWT_SECRET_TOKEN}


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_CALLBACK_URI}

  authorization-uri: ${KAKAO_AUTH_URI}
  token-uri: ${KAKAO_TOKEN_URI}
  user-info-uri: ${KAKAO_USER_INFO_URI}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  redirect-uri: ${GOOGLE_CALLBACK_URI}
  client-secret: ${GOOGLE_SECRET}

  authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
  token-uri: ${GOOGLE_TOKEN_URI}
  user-info-uri: ${GOOGLE_USER_INFO_URI}


file:
  upload-dir: ${FILE_PATH}
  schema: ${SCHEMA}


