

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/knufest?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&cacheDefaultTimezone=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG

jwt:
  secret: "DLbuFF+XhYWRCzk7QFmob8DDUosRZRfln8XGytbEGcAcmpcU/++KO3wBTuDG4g6k3p3LpMJxA2CUivG6YpkLzQ=="

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: "AKIAQFC264AN5HSFAHOY"
      secret-key: "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"
    s3:
      bucket: "pium-bucket"

kakao:
  client-id: "648fcdc9b3865f050600b4295810e763"
  redirect-uri: "http://localhost:8080/api/v1/oauth/kakao/callback"

  authorization-uri: "https://kauth.kakao.com/oauth/authorize"
  token-uri: "https://kauth.kakao.com/oauth/token"
  user-info-uri: "https://kapi.kakao.com/v2/user/me"

google:
  client-id: "508444563994-of6s3lm7ehjt289026qmro8hd1pqgai5.apps.googleusercontent.com"
  redirect-uri: "http://localhost:8080/api/v1/oauth/google/callback"
  client-secret: "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"

  authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
  token-uri: "https://oauth2.googleapis.com/token"
  user-info-uri: "https://www.googleapis.com/oauth2/v2/userinfo"



