name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DOMAIN_PATH=${{ secrets.DOMAIN_PATH }}" >> $GITHUB_ENV

      - name: Build and run Docker containers
        run: docker-compose up --build -d

      - name: Clean up old Docker images
        if: always()
        run: docker image prune -f

